import { Stack, Text, Heading, Badge, Card } from "@renge-ui/react";
import { Demo, Code, Callout, ComponentSection } from "@/components/ui/DocPrimitives";

export function AnimationsDocs() {
  return (
    <ComponentSection id="animations" title="Animations" description="15 named animations derived from the token system. Apply via the animation prop on any component, or directly via the CSS variable.">
      <Demo label="All 15 tokens">
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))", gap: "var(--renge-space-3)", width: "100%" }}>
          {[
            "vortex-reveal", "helix-rise", "sacred-fade", "spiral-in",
            "morph-fade-in", "bloom", "pulse", "vibrate",
            "wave", "breathe", "fall", "float",
            "float-wave", "pulse-color-shift", "swelling",
          ].map(name => (
            <div key={name} style={{ padding: "var(--renge-space-2) var(--renge-space-3)", borderRadius: "var(--renge-radius-2)", border: "1px solid var(--renge-color-border-subtle)", background: "var(--renge-color-bg)" }}>
              <Text size="sm" style={{ fontFamily: "var(--font-mono, monospace)" }}>{name}</Text>
            </div>
          ))}
        </div>
      </Demo>
      <Demo label="Live examples">
        <Heading level={3} animation="breathe">breathe</Heading>
        <Text size="lg" animation="float">float</Text>
        <span style={{ animation: "var(--renge-animation-pulse)" }}><Badge variant="accent">pulse</Badge></span>
        <Card variant="outlined" padding="3" animation="bloom">
          <Text size="sm">bloom</Text>
        </Card>
      </Demo>
      <Code>{`{/* animation prop — available on Heading, Text, Card, Section, Badge, and more */}
<Heading level={2} animation="breathe">Living proportion.</Heading>
<Badge variant="accent" animation="pulse">New</Badge>
<Card animation="bloom"><Text>Enters with bloom.</Text></Card>

{/* Via CSS variable — works on any element */}
<div style={{ animation: "var(--renge-animation-float)" }}>
  Floats gently.
</div>

{/* Duration tokens govern speed — Fibonacci × 100ms */}
/* breathe → var(--renge-duration-10) = 8900ms  (slow, organic) */
/* vibrate → var(--renge-duration-6)  = 1300ms  (quick, alert)  */`}</Code>
      <Callout>
        All 15 <code>@keyframes</code> blocks and their <code>--renge-animation-*</code> CSS variables are generated by <code>createRengeTheme()</code> — no separate import needed. Durations reference <code>--renge-duration-*</code> tokens derived from Fibonacci × 100ms.
      </Callout>

      <Stack gap="3">
        <Heading level={3} size="lg">Duration reference</Heading>
        <div style={{ overflowX: "auto", borderRadius: "var(--renge-radius-2)", border: "1px solid var(--renge-color-border-subtle)" }}>
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead>
              <tr style={{ background: "var(--renge-color-bg-subtle)" }}>
                {["Token", "Value", "Fibonacci derivation"].map(h => (
                  <th key={h} style={{ padding: "var(--renge-space-2) var(--renge-space-4)", textAlign: "left", fontSize: "var(--renge-font-size-sm)", color: "var(--renge-color-fg-subtle)", fontWeight: 600, letterSpacing: "0.06em", textTransform: "uppercase", borderBottom: "1px solid var(--renge-color-border-subtle)" }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {([
                ["--renge-duration-1",  "100ms",  "Fib 1 × 100ms"],
                ["--renge-duration-2",  "200ms",  "Fib 2 × 100ms"],
                ["--renge-duration-3",  "300ms",  "Fib 3 × 100ms"],
                ["--renge-duration-4",  "500ms",  "Fib 5 × 100ms"],
                ["--renge-duration-5",  "800ms",  "Fib 8 × 100ms — motion default"],
                ["--renge-duration-6",  "1300ms", "Fib 13 × 100ms"],
                ["--renge-duration-7",  "2100ms", "Fib 21 × 100ms — toast timeout"],
                ["--renge-duration-8",  "3400ms", "Fib 34 × 100ms"],
                ["--renge-duration-9",  "5500ms", "Fib 55 × 100ms — most animations"],
                ["--renge-duration-10", "8900ms", "Fib 89 × 100ms — breathe, bloom"],
              ] as [string, string, string][]).map(([tok, val, note]) => (
                <tr key={tok}>
                  <td style={{ padding: "var(--renge-space-2) var(--renge-space-4)", fontFamily: "var(--font-mono, monospace)", fontSize: "var(--renge-font-size-sm)", color: "var(--renge-color-accent)", borderBottom: "1px solid var(--renge-color-border-subtle)", whiteSpace: "nowrap" }}>{tok}</td>
                  <td style={{ padding: "var(--renge-space-2) var(--renge-space-4)", fontFamily: "var(--font-mono, monospace)", fontSize: "var(--renge-font-size-sm)", color: "var(--renge-color-fg-subtle)", borderBottom: "1px solid var(--renge-color-border-subtle)", whiteSpace: "nowrap" }}>{val}</td>
                  <td style={{ padding: "var(--renge-space-2) var(--renge-space-4)", fontSize: "var(--renge-font-size-sm)", color: "var(--renge-color-fg-muted)", borderBottom: "1px solid var(--renge-color-border-subtle)" }}>{note}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Stack>
    </ComponentSection>
  );
}
