/**
 * framework-parity.mjs
 *
 * Generates docs/framework-parity.md — the honest cross-framework component
 * coverage matrix (react / vue / svelte), computed from each package's built
 * public API (dist/index.d.ts). Regenerate after adding/removing components:
 *
 *   pnpm build && node scripts/framework-parity.mjs
 *
 * React is the reference implementation; Vue and Svelte are ports. This makes
 * the gap between them explicit instead of implied.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FRAMEWORKS = ['react', 'vue', 'svelte'];

// Exports that are types / utilities / theming / constants, not renderable
// components.
const NOT_A_COMPONENT =
  /(Props|Context|Return|Config|Variant|Name|Theme|Mode)$|^(CSS)/;
const UTIL_EXPORTS = new Set([
  'RengeStylesheet', 'RengeProvider', 'ToastProvider', 'useRenge',
  // constants re-exported from @renge-ui/tokens (all-caps math/token values)
  'PHI', 'FIBONACCI', 'GOLDEN_ANGLE', 'ANIMATION_NAMES',
]);

function componentsOf(pkg) {
  const dts = resolve(root, `packages/${pkg}/dist/index.d.ts`);
  if (!existsSync(dts)) throw new Error(`build ${pkg} first — missing ${dts}`);
  const src = readFileSync(dts, 'utf8');
  const names = new Set();
  for (const m of src.matchAll(
    /\b(?:declare (?:const|function|class)|export (?:const|function|class))\s+([A-Z][A-Za-z0-9]+)/g,
  ))
    names.add(m[1]);
  for (const block of src.matchAll(/export\s*\{([^}]+)\}/g))
    for (const raw of block[1].split(',')) {
      const t = raw.trim().split(/\s+as\s+/).pop().trim();
      if (/^[A-Z][A-Za-z0-9]+$/.test(t)) names.add(t);
    }
  return new Set([...names].filter((n) => !NOT_A_COMPONENT.test(n) && !UTIL_EXPORTS.has(n)));
}

const sets = Object.fromEntries(FRAMEWORKS.map((f) => [f, componentsOf(f)]));
const all = [...new Set(FRAMEWORKS.flatMap((f) => [...sets[f]]))].sort((a, b) =>
  a.localeCompare(b),
);
const has = (f, c) => sets[f].has(c);
const inAll = all.filter((c) => FRAMEWORKS.every((f) => has(f, c)));
const reactOnly = all.filter((c) => has('react', c) && !has('vue', c) && !has('svelte', c));
const other = all.filter((c) => !inAll.includes(c) && !reactOnly.includes(c));

const pct = (f) => Math.round((sets[f].size / sets.react.size) * 100);

const lines = [];
lines.push('# Framework parity');
lines.push('');
lines.push('> Generated by `scripts/framework-parity.mjs` from each package\'s built');
lines.push('> `dist/index.d.ts`. **Do not edit by hand** — run the script to refresh.');
lines.push('');
lines.push(
  'React is the **reference implementation**; Vue and Svelte are ports. This table is the honest coverage picture rather than an implied "supported everywhere."',
);
lines.push('');
lines.push('| Framework | Components | Coverage vs React |');
lines.push('|-----------|-----------|-------------------|');
for (const f of FRAMEWORKS)
  lines.push(`| \`@renge-ui/${f}\` | ${sets[f].size} | ${f === 'react' ? '— (reference)' : pct(f) + '%'} |`);
lines.push('');
lines.push(`## React-only — the parity gap (${reactOnly.length})`);
lines.push('');
lines.push(
  'Present in React, **absent from Vue and Svelte**. These are the hard interactive / floating-overlay primitives (focus management, positioning, keyboard nav) plus a few visual components — exactly the pieces that are most work to port:',
);
lines.push('');
for (const c of reactOnly) lines.push(`- \`${c}\``);
lines.push('');
lines.push(`## In all three (${inAll.length})`);
lines.push('');
lines.push('The shared core — structural, form, and layout components:');
lines.push('');
lines.push(inAll.map((c) => `\`${c}\``).join(' · '));
if (other.length) {
  lines.push('');
  lines.push(`## Partial / framework-specific (${other.length})`);
  lines.push('');
  lines.push('| Component | ' + FRAMEWORKS.map((f) => f).join(' | ') + ' |');
  lines.push('|' + '---|'.repeat(FRAMEWORKS.length + 1));
  for (const c of other)
    lines.push(`| \`${c}\` | ` + FRAMEWORKS.map((f) => (has(f, c) ? '✓' : '·')).join(' | ') + ' |');
}
lines.push('');

writeFileSync(resolve(root, 'docs/framework-parity.md'), lines.join('\n'), 'utf8');
console.log(
  `✓ docs/framework-parity.md — react ${sets.react.size}, vue ${sets.vue.size} (${pct('vue')}%), svelte ${sets.svelte.size} (${pct('svelte')}%); ${reactOnly.length} react-only`,
);
